<a href="https://colab.research.google.com/github/avinashronanki/ML/blob/master/nn_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import torch
import torch.nn as nn
from torch.nn import functional as F

import pandas as pd
import numpy as np

dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')

dataset.describe()

dataset.head()

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Xtrain_ = torch.from_numpy(X_train).float()
Xtest_ = torch.from_numpy(X_test).float()

Xtrain_

ytrain_ = torch.from_numpy(y_train)
ytest_ = torch.from_numpy(y_test)

ytrain_

Xtrain_.shape, ytrain_.shape

Xtest_.shape, ytest_.shape

input_size=2
output_size=2
hidden_size=10

class Net(nn.Module):
   def __init__(self):
       super(Net, self).__init__()
       self.fc1 = torch.nn.Linear(input_size, hidden_size)
       self.fc2 = torch.nn.Linear(hidden_size, hidden_size)
       self.fc3 = torch.nn.Linear(hidden_size, output_size)


   def forward(self, X):
       X = torch.relu((self.fc1(X)))
       X = torch.relu((self.fc2(X)))
       X = self.fc3(X)

       return F.log_softmax(X,dim=1)

model = Net()

import torch.optim as optim
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.NLLLoss()

epochs = 100

for epoch in range(epochs):
  optimizer.zero_grad()
  Ypred = model(Xtrain_)
  loss = loss_fn(Ypred,  ytrain_)
  loss.backward()
  optimizer.step()
  print('Epoch',epoch, 'loss',loss.item())

list(model.parameters())

torch.from_numpy(sc.transform(np.array([[40,20000]]))).float()

y_cust_20_40000 = model(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000

_, predicted_20_40000 = torch.max(y_cust_20_40000.data,-1)
predicted_20_40000

y_cust_42_50000 = model(torch.from_numpy(sc.transform(np.array([[42,50000]]))).float())
y_cust_42_50000

_, predicted_42_50000 = torch.max(y_cust_42_50000.data,-1)
predicted_42_50000

torch.save(model,'customer_buy.pt')

!ls

restored_model = torch.load('customer_buy.pt')

y_cust_20_40000 = restored_model(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000

_, predicted_20_40000 = torch.max(y_cust_20_40000.data,-1)
predicted_20_40000

model.state_dict()

torch.save(model.state_dict(),'customer_buy_state_dict')

!ls

new_predictor = Net()

y_cust_20_40000 = new_predictor(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000

!zip -r customer_buy_state_dict.zip customer_buy_state_dict

!ls

from google.colab import files

files.download('customer_buy_state_dict.zip')



In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

import pandas as pd
import numpy as np


In [ ]:

dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')

dataset.describe()

dataset.head()

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [4]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [6]:

from sklearn.preprocessing import StandardScaler # scale the data 
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
Xtrain_ = torch.from_numpy(X_train).float()  # converting into tensor 
Xtest_ = torch.from_numpy(X_test).float()

Xtrain_

In [8]:
ytrain_ = torch.from_numpy(y_train) # converting into tensor 
ytest_ = torch.from_numpy(y_test)

ytrain_

tensor([1, 1, 1,  ..., 1, 1, 0])

In [10]:
Xtrain_.shape, ytrain_.shape # train shape 



(torch.Size([1243, 2]), torch.Size([1243]))

In [ ]:
Xtest_.shape, ytest_.shape #test shape 

In [13]:
input_size=2 
output_size=2
hidden_size=10
epochs = 100

In [12]:
class Net(nn.Module): #tpical NN class 
   def __init__(self):
       super(Net, self).__init__()
       self.fc1 = torch.nn.Linear(input_size, hidden_size) # fully connected layer 
       self.fc2 = torch.nn.Linear(hidden_size, hidden_size) # fully connected hidden layer 
       self.fc3 = torch.nn.Linear(hidden_size, output_size)


   def forward(self, X):
       X = torch.relu((self.fc1(X))) # relu activation function 
       X = torch.relu((self.fc2(X)))
       X = self.fc3(X)

       return F.log_softmax(X,dim=1) # softmax layer for probablity 

model = Net()

In [15]:
import torch.optim as optim
optimizer = torch.optim.Adam(model.parameters(), lr=0.01) #optimizer learning rate 
loss_fn = nn.NLLLoss() # loss fuction 

In [ ]:
for epoch in range(epochs): # training the model 
  optimizer.zero_grad()
  Ypred = model(Xtrain_)
  loss = loss_fn(Ypred,  ytrain_)
  loss.backward()
  optimizer.step()
  print('Epoch',epoch, 'loss',loss.item())

In [ ]:

list(model.parameters())

In [18]:

torch.from_numpy(sc.transform(np.array([[40,20000]]))).float() # test 

tensor([[   40., 20000.]])

In [19]:
y_cust_20_40000 = model(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000

tensor([[-103388.2812,       0.0000]], grad_fn=<LogSoftmaxBackward>)

In [20]:
_, predicted_20_40000 = torch.max(y_cust_20_40000.data,-1)  # prediction class 
predicted_20_40000

tensor([1])

In [21]:
y_cust_42_50000 = model(torch.from_numpy(sc.transform(np.array([[42,50000]]))).float())
y_cust_42_50000

tensor([[-258402.4531,       0.0000]], grad_fn=<LogSoftmaxBackward>)

In [22]:
_, predicted_42_50000 = torch.max(y_cust_42_50000.data,-1)
predicted_42_50000

tensor([1])

In [23]:
torch.save(model,'customer_buy.pt') # save the model

In [24]:
restored_model = torch.load('customer_buy.pt') # using the saved model 



In [25]:
y_cust_20_40000 = restored_model(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000



tensor([[-103388.2812,       0.0000]], grad_fn=<LogSoftmaxBackward>)

In [26]:
_, predicted_20_40000 = torch.max(y_cust_20_40000.data,-1)
predicted_20_40000

tensor([1])

In [27]:
model.state_dict() # weight of the model can be assessed 



OrderedDict([('fc1.weight', tensor([[ 0.7236,  0.3059],
                      [ 0.0572,  0.6705],
                      [ 0.6397,  0.2669],
                      [ 0.4604, -0.1189],
                      [ 0.4668,  0.8093],
                      [ 0.8860, -0.2701],
                      [ 0.4740,  0.6894],
                      [-0.9594,  0.8412],
                      [-1.0037, -0.8508],
                      [-0.9141, -0.3944]])),
             ('fc1.bias',
              tensor([ 0.4523,  0.5265,  0.8296,  1.1094,  0.4882, -0.0092, -0.2761,  0.3868,
                       0.5546,  0.6235])),
             ('fc2.weight',
              tensor([[ 0.1189, -0.1439, -0.1744, -0.2777,  0.1959, -0.1289,  0.0303, -0.1794,
                       -0.0040, -0.1330],
                      [ 0.1773, -0.2261, -0.3219,  0.2010, -0.2538, -0.1496,  0.0610, -0.1575,
                        0.1278, -0.3253],
                      [-0.0571,  0.1791,  0.1864, -0.3067, -0.3453,  0.0714,  0.0831, -0.2975,
   

In [28]:
torch.save(model.state_dict(),'customer_buy_state_dict') # prefered way to save the model 

In [29]:
new_predictor = Net() #using the dict save model 





In [30]:
y_cust_20_40000 = new_predictor(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000

tensor([[-1053.1417,     0.0000]], grad_fn=<LogSoftmaxBackward>)

In [31]:
_, predicted_20_40000 = torch.max(y_cust_20_40000.data,-1)
predicted_20_40000

tensor([1])

In [32]:

!zip -r customer_buy_state_dict.zip customer_buy_state_dict

  adding: customer_buy_state_dict (deflated 47%)


In [33]:
from google.colab import files

files.download('customer_buy_state_dict.zip')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>