<a href="https://colab.research.google.com/github/avinashronanki/ML/blob/main/pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
!git clone https://github.com/avinashronanki/ML.git

Cloning into 'ML'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 19 (delta 4), reused 15 (delta 4), pack-reused 0
Unpacking objects: 100% (19/19), done.


In [11]:
%cd /content/ML

/content/ML


In [1]:
!wget https://github.com/avinashronanki/ML/blob/main/classifier.pickle

--2020-11-09 18:47:21--  https://github.com/avinashronanki/ML/blob/main/classifier.pickle
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘classifier.pickle’

classifier.pickle       [ <=>                ]  77.77K  --.-KB/s    in 0.03s   

2020-11-09 18:47:21 (2.84 MB/s) - ‘classifier.pickle’ saved [79633]



In [2]:
!wget https://github.com/avinashronanki/ML/blob/main/sc.pickle

--2020-11-09 18:47:54--  https://github.com/avinashronanki/ML/blob/main/sc.pickle
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘sc.pickle’

sc.pickle               [ <=>                ]  77.61K  --.-KB/s    in 0.03s   

2020-11-09 18:47:55 (2.86 MB/s) - ‘sc.pickle’ saved [79477]



In [8]:
import numpy as np

import pandas as pd
import pickle

In [9]:
classifier_colab = pickle.load(open('/content/classifier.pickle','rb'))

UnpicklingError: ignored

In [12]:
classifier_colab = pickle.load(open('/content/ML/classifier.pickle','rb'))

scaler_colab = pickle.load(open('/content/ML/sc.pickle','rb'))

/usr/local/lib/python3.6/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 0.23.0 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator StandardScaler from version 0.23.0 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [13]:
new_pred = classifier_colab.predict(scaler_colab.transform(np.array([[40,20000]])))

new_pred

array([0])

In [14]:
new_pred_proba = classifier_colab.predict_proba(scaler_colab.transform(np.array([[40,20000]])))[:,1]
new_pred_proba

array([0.2])

In [15]:
new_pred_2 = classifier_colab.predict(scaler_colab.transform(np.array([[42,50000]])))
new_pred_proba_2 = classifier_colab.predict_proba(scaler_colab.transform(np.array([[42,50000]])))[:,1]
new_pred_2

array([1])

In [16]:
new_pred_proba_2

array([0.8])